CREATE TABLE Users (
    UID INTEGER PRIMARY KEY,
    Name TEXT NOT NULL,
    Firstname TEXT NOT NULL,
    DOB DATE NOT NULL,
    CA INTEGER,
    FOREIGN KEY(CA) REFERENCES Classes(CA)
);

CREATE TABLE Login (
    NR INTEGER PRIMARY KEY AUTOINCREMENT,
    Time TIMESTAMP NOT NULL,
    UID INTEGER,
    FOREIGN KEY(UID) REFERENCES Users(UID)
);

CREATE TABLE Logoff (
    NR INTEGER PRIMARY KEY AUTOINCREMENT,
    Time TIMESTAMP NOT NULL,
    UID INTEGER,
    FOREIGN KEY(UID) REFERENCES Users(UID)
);

CREATE TABLE Admins (
    Username TEXT PRIMARY KEY,
    Password TEXT NOT NULL,
    UID INTEGER,
    FOREIGN KEY(UID) REFERENCES Users(UID)
);

CREATE TABLE Classes (
    CA INTEGER PRIMARY KEY,
    Subject_area TEXT NOT NULL,
    Classroom TEXT NOT NULL
);
